spring:
  application:
    name: job-scheduler-prometheus

  cassandra:
    keyspace-name: job_scheduler
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

# Expose Prometheus endpoint via Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8080

# Default configuration (Moderate creation, moderate TTL)
app:
  scheduler:
    fixed-rate: 5000
    ttl-min: 0
    ttl-max: 60
  executor:
    fixed-rate: 2000

---
spring:
  config:
    activate:
      on-profile: high-queue
app:
  scheduler:
    fixed-rate: 100
    ttl-min: 60
    ttl-max: 120
  executor:
    fixed-rate: 2000

---
spring:
  config:
    activate:
      on-profile: fast-exec
app:
  scheduler:
    fixed-rate: 3000
    ttl-min: 0
    ttl-max: 3
  executor:
    fixed-rate: 500
